-- UPDATE
-- The UPDATE command is used to modify existing data in a table.

CREATE DATABASE COLLEGE;
USE COLLEGE;
CREATE TABLE STUDENT(
	ID INT PRIMARY KEY,
    NAME VARCHAR(100),
    CITY VARCHAR(100),
    MARKS INT);
INSERT INTO STUDENT
VALUES
(1,'SIVA','HYDRABAD',95),
(2,'RAVI','KHAMMAM',85),
(3,'NAVEEN','WARANGLE',89),
(4,'MAHI','SATUPALLY',65),
(5,'NANI','RAMACHANDRAPURAM',99);

SELECT *
FROM STUDENT;

UPDATE STUDENT
SET CITY='SATUPALLY'
WHERE ID=5;

UPDATE STUDENT
SET MARKS=99
WHERE ID=1;

UPDATE STUDENT
SET NAME='SHIVA'
WHERE ID=1;

UPDATE STUDENT
SET CITY = 'RAMACHANDRAPURAM',
    MARKS = 97
WHERE ID = 1;