-- DELETE
-- The DELETE command is used to remove rows from a table.

CREATE DATABASE COLLEGE;
USE COLLEGE;
CREATE TABLE STUDENT(
	ID INT PRIMARY KEY,
    NAME VARCHAR(100),
    CITY VARCHAR(100),
    MARKS INT);
INSERT INTO STUDENT
VALUES
(1,'SIVA','HYDRABAD',95),
(2,'RAVI','KHAMMAM',85),
(3,'NAVEEN','WARANGLE',89),
(4,'MAHI','SATUPALLY',65),
(5,'NANI','RAMACHANDRAPURAM',99);

SELECT *
FROM STUDENT;

-- DELETE FROM STUDENT
-- WHERE ID=5;	

DE-- DELETE
-- The DELETE command is used to remove rows from a table.

CREATE DATABASE COLLEGE;
USE COLLEGE;
CREATE TABLE STUDENT(
	ID INT PRIMARY KEY,
    NAME VARCHAR(100),
    CITY VARCHAR(100),
    MARKS INT);
INSERT INTO STUDENT
VALUES
(1,'SIVA','HYDRABAD',95),
(2,'RAVI','KHAMMAM',85),
(3,'NAVEEN','WARANGLE',89),
(4,'MAHI','SATUPALLY',65),
(5,'NANI','RAMACHANDRAPURAM',99);

SELECT *
FROM STUDENT;

DELETE FROM STUDENT
WHERE ID=5;	

DELETE FROM STUDENT
WHERE ID=2;