-- ALTER TABLE
-- ALTER TABLE is used to modify the structure of an existing table.
-- You can use it to:
-- Add a column 
-- Modify a column
-- Rename a column
-- Drop a column

CREATE DATABASE COLLEGE;
USE COLLEGE;
CREATE TABLE STUDENT(
	ID INT PRIMARY KEY,
    NAME VARCHAR(100),
    CITY VARCHAR(100),
    MARKS INT);
INSERT INTO STUDENT
VALUES
(1,'SIVA','HYDRABAD',95),
(2,'RAVI','KHAMMAM',85),
(3,'NAVEEN','WARANGLE',89),
(4,'MAHI','SATUPALLY',65),
(5,'NANI','RAMACHANDRAPURAM',99);

SELECT *
FROM STUDENT;

ALTER TABLE STUDENT
ADD EMAIL VARCHAR(100);

ALTER TABLE STUDENT
MODIFY EMAIL VARCHAR(150);

ALTER TABLE STUDENT
RENAME COLUMN NAME TO STUDENT_NAME;

ALTER TABLE STUDENT
DROP COLUMN EMAIL;
