CREATE DATABASE COMPENY;
USE COMPENY;
CREATE TABLE DEPARTMENT(
	DEPARTMENT_ID INT PRIMARY KEY,
    DEPARTMENT_NAME VARCHAR(100));
INSERT INTO DEPARTMENT
VALUES
(1,'PYTHON'),
(2,'JAVA'),
(3,'SQL');
CREATE TABLE EMPLOYEES(
	EMPLOYEE_ID INT ,
    NAME VARCHAR(100),
    DEPARTMENT_ID INT,
    SALARY INT);
INSERT INTO EMPLOYEES
VALUES
(1,'SIVA',1,40000),
(2,'RAVI',2,50000),
(3,'NAAEEN',3,45000),
(4,'MAHI',3,60000),
(5,'NANI',1,65000);

SELECT *
FROM EMPLOYEES
WHERE SALARY < ALL (
	SELECT SALARY
    FROM EMPLOYEES
    WHERE DEPARTMENT_ID=2);
