-- Stored Functions
-- A Stored Function is similar to a stored procedure, but a function must return a value.

CREATE DATABASE COLLEGE;
USE COLLEGE;
CREATE TABLE STUDENT(
	ID INT PRIMARY KEY,
    NAME VARCHAR(100),
    CITY VARCHAR(100),
    MARKS INT);
INSERT INTO STUDENT
VALUES
(1,'SIVA','HYDRABAD',95),
(2,'RAVI','KHAMMAM',85),
(3,'NAVEEN','WARANGLE',82),
(4,'MAHI','SATUPALLI',93),
(5,'NANI','LANKAPALLI',89);


DELIMITER //

CREATE FUNCTION TOTAL_MARKS(MONTHLY_MARKS INT)
RETURNS INT
DETERMINISTIC
BEGIN
    RETURN MONTHLY_MARKS* 12;
END //

DELIMITER ;

SELECT NAME, MARKS, TOTAL_MARKS(MARKS) AS YEARLY_MARKS
FROM STUDENT;