-- TRIGGERS
-- A Trigger is automatically executed when a specific event occurs on a table.
-- Common events:
-- INSERT
-- UPDATE
-- DELETE

CREATE DATABASE COLLEGE;
USE COLLEGE;

CREATE TABLE STUDENT(
    ID INT,
    NAME VARCHAR(100),
    CITY VARCHAR(100),
    MARKS INT
);

INSERT INTO STUDENT
VALUES
(1, 'SIVA', 'HYDRABAD', 95),
(2, 'RAVI', 'KHAMMAM', 85),
(3, 'NAVEEN', 'WARANGLE', 82),
(4, 'MAHI', 'SATUPALLI', 93),
(5, 'NANI', 'LANKAPALLI', 89);

CREATE TABLE STUDENT_LOG(
    ID INT,
    NAME VARCHAR(100),
    MARKS INT
);

DELIMITER //

CREATE TRIGGER AFTER_STUDENT_INSERT
AFTER INSERT ON STUDENT
FOR EACH ROW
BEGIN
    INSERT INTO STUDENT_LOG(ID, NAME, MARKS)
    VALUES (NEW.ID, NEW.NAME, NEW.MARKS);
END //

DELIMITER ;

-- Insert a new student
INSERT INTO STUDENT
VALUES (6, 'RAHUL', 'HYDERABAD', 90);

-- Check STUDENT table
SELECT * FROM STUDENT;

-- Check STUDENT_LOG table
SELECT * FROM STUDENT_LOG;