-- Transactions
-- A Transaction is a group of SQL operations treated as one unit of work.
	
CREATE DATABASE COLLEGE;
USE COLLEGE;
CREATE TABLE STUDENT(
	ID INT PRIMARY KEY,
    NAME VARCHAR(100),
    CITY VARCHAR(100),
    MARKS INT);
INSERT INTO STUDENT
VALUES
(1,'SIVA','HYDRABAD',95),
(2,'RAVI','KHAMMAM',85),
(3,'NAVEEN','WARANGLE',82),
(4,'MAHI','SATUPALLI',93),
(5,'NANI','LANKAPALLI',89);

UPDATE STUDENT
SET MARKS = MARKS - 10
WHERE ID = 1;

UPDATE STUDENT
SET MARKS = MARKS - 10
WHERE ID = 2;

SELECT * FROM STUDENT;
