-- COMMIT
-- COMMIT permanently saves the changes made during a transaction.

CREATE DATABASE COLLEGE;
USE COLLEGE;
CREATE TABLE STUDENT(
	ID INT PRIMARY KEY,
    NAME VARCHAR(100),
    CITY VARCHAR(100),
    MARKS INT);
INSERT INTO STUDENT
VALUES
(1,'SIVA','HYDRABAD',95),
(2,'RAVI','KHAMMAM',85),
(3,'NAVEEN','WARANGLE',82),
(4,'MAHI','SATUPALLI',93),
(5,'NANI','LANKAPALLI',89);

SELECT * FROM STUDENT;

UPDATE STUDENT
SET MARKS = MARKS - 10
WHERE ID = 1;

UPDATE STUDENT
SET MARKS = MARKS - 10
WHERE ID = 2;
SELECT * FROM STUDENT;
COMMIT;