-- SAVEPOINT
-- A SAVEPOINT creates a checkpoint inside a transaction.

CREATE DATABASE COLLEGE;
USE COLLEGE;
CREATE TABLE STUDENT(
	ID INT PRIMARY KEY,
    NAME VARCHAR(100),
    CITY VARCHAR(100),
    MARKS INT);
INSERT INTO STUDENT
VALUES
(1,'SIVA','HYDRABAD',95),
(2,'RAVI','KHAMMAM',85),
(3,'NAVEEN','WARANGLE',82),
(4,'MAHI','SATUPALLI',93),
(5,'NANI','LANKAPALLI',89);

SELECT * FROM STUDENT;
START TRANSACTION;
UPDATE STUDENT
SET MARKS = 65
WHERE ID = 1;
SAVEPOINT MARKS_UPDATE;
UPDATE STUDENT
SET MARKS = 55
WHERE ID = 2;
ROLLBACK TO MARKS_UPDATE;
SELECT * FROM STUDENT;
COMMIT;