-- NOT NULL
CREATE DATABASE COLLAGE;
USE COLLAGE;
CREATE TABLE STUDENT(ID INT NOT NULL,NAME VARCHAR(50) NOT NULL,CLASS INT NOT NULL,EMAIL VARCHAR(100));
INSERT INTO STUDENT
VALUES(1,'SIVA',12,'SIVA@GMAIL.COM');
INSERT INTO STUDENT
VALUES(2,'NANI',12,'NANI@GMAIL.COM'),(3,'MANI',12,'MANI@GMAIL.COM'),(4,'NAVEEN',12,'NAVEEN@GMAIL.COM');
SELECT * FROM STUDENT;