-- FOREIGN KEY
CREATE DATABASE INSTITUT;
USE INSTITUT;
CREATE TABLE DEPARMENT(DEPARMENT_ID INT PRIMARY KEY,DEPARMENT_NAME VARCHAR(100) UNIQUE);
INSERT INTO DEPARMENT
VALUES(1,'PYTHON'),(2,'JAVA'),(3,'SQL');
SELECT * FROM DEPARMENT;