-- SELF JOIN
-- A Self Join is when a table is joined with itself.

CREATE DATABASE COMPENY;
USE COMPENY;

CREATE TABLE EMPLOYEES(
    EMPLOYEE_ID INT PRIMARY KEY,
    NAME VARCHAR(100),
    MANAGER_ID INT
);

INSERT INTO EMPLOYEES
VALUES
(1, 'SIVA', NULL),
(2, 'NANI', 1),
(3, 'NAVEEN', 1),
(4, 'MAHI', 2);

SELECT
    EMPLOYEE.NAME AS EMPLOYEE,
    MANAGER.NAME AS MANAGER
FROM EMPLOYEES AS EMPLOYEE
LEFT JOIN EMPLOYEES AS MANAGER
ON EMPLOYEE.MANAGER_ID = MANAGER.EMPLOYEE_ID;