-- UPPER()
-- Converts text into uppercase.
CREATE DATABASE COLLAGE;
USE COLLAGE;
CREATE TABLE STUDENT
	(ID INT PRIMARY KEY AUTO_INCREMENT,
	NAME VARCHAR(100) NOT NULL,
	AGE INT CHECK(AGE>=10),
	CITY VARCHAR(100) NOT NULL,
	MARKS INT NOT NULL,
	EMAIL VARCHAR(100) NOT NULL);
INSERT INTO STUDENT(NAME,AGE,CITY,MARKS,EMAIL)
VALUES
('siva',22,'HYDRABAD',82,'SIVA@GMAIL.COM'),
('RAVI',25,'KHAMMAM',95,'RAVI@GMAIL.COM'),
('NAVEEN',23,'warangle',80,'NAVEEN@GMAIL.COM'),
('dhanush',25,'KHAMMAM',85,'DHANUSH@GMAIL.COM'),
('SATISH',24,'HYDRABAD',90,'SATISH@GMAIL.COM'),
('RAMU',22,'WARANGLE',87,'RAMU@GMAIL.COM'),
('ravi',27,'KHAMMAM',60,'RANI@GMAIL.COM'),
('HEMA',22,'SATUPALLY',40,'HEMA@GMAIL.COM'),
('VIDYA',29,'WARANGLE',30,'VIDYA@GMAIL.COM');

SELECT UPPER(NAME) FROM STUDENT;
SELECT UPPER(city) FROM STUDENT;