-- LIKE
--  LIKE is used for pattern matching, especially with text.
-- There are two important wildcards:
--  % → any number of characters
--  _ → exactly one character
CREATE DATABASE COLLAGE;
USE COLLAGE;
CREATE TABLE STUDENT(
ID INT PRIMARY KEY AUTO_INCREMENT,
NAME VARCHAR(100) NOT NULL,
AGE INT CHECK(AGE>=18),
CITY VARCHAR(100) NOT NULL,
MARKS INT NOT NULL,
EMAIL VARCHAR(100) UNIQUE
);
INSERT INTO STUDENT(NAME,AGE,CITY,MARKS,EMAIL)
VALUES
('SIVA',22,'HYDRABAD',82,'SIVA@GMAIL.COM'),
('RAVI',25,'KHAMMAM',95,'RAVI@GMAIL.COM'),
('NAVEEN',23,'WARANGLE',80,'NAVEEN@GMAIL.COM'),
('DHANUSH',25,'KHAMMAM',85,'DHANUSH@GMAIL.COM'),
('SATISH',24,'HYDRABAD',90,'SATISH@GMAIL.COM'),
('RAMU',22,'WARANGLE',87,'RAMU@GMAIL.COM'),
('RANI',27,'KHAMMAM',60,'RANI@GMAIL.COM'),
('HEMA',22,'SATUPALLY',40,'HEMA@GMAIL.COM'),
('VIDYA',29,'WARANGLE',30,'VIDYA@GMAIL.COM');

-- Starts with S
SELECT * FROM STUDENT
WHERE NAME LIKE "S%";
-- Starts with H
SELECT * FROM STUDENT
WHERE NAME LIKE "H%";
-- END WITH I
SELECT * FROM STUDENT
WHERE NAME LIKE "%I";
-- END WITH H
SELECT * FROM STUDENT
WHERE NAME LIKE "%H";
-- Contains A
SELECT * FROM STUDENT
WHERE NAME LIKE "%A%";
-- Contains S
SELECT * FROM STUDENT
WHERE NAME LIKE "%S%";
-- Exactly 4 characters
SELECT * FROM STUDENT
WHERE NAME LIKE '____';
-- Exactly 5 characters
SELECT * FROM STUDENT
WHERE NAME LIKE '_____';
-- Each _ represents one character.