-- WHERE
CREATE DATABASE COLLAGE;
USE COLLAGE;
CREATE TABLE STUDENT(
ID INT PRIMARY KEY AUTO_INCREMENT,
NAME VARCHAR(100) NOT NULL,
AGE INT CHECK(AGE>=18),
CITY VARCHAR(100) NOT NULL,
MARKS INT NOT NULL,
EMAIL VARCHAR(100) UNIQUE
);
INSERT INTO STUDENT(NAME,AGE,CITY,MARKS,EMAIL)
VALUES
('SIVA',22,'HYDRABAD',82,'SIVA@GMAIL.COM'),
('RAVI',25,'KHAMMAM',95,'RAVI@GMAIL.COM'),
('NAVEEN',23,'WARANGLE',80,'NAVEEN@GMAIL.COM'),
('DHANUSH',25,'KHAMMAM',85,'DHANUSH@GMAIL.COM'),
('SATISH',24,'HYDRABAD',90,'SATISH@GMAIL.COM'),
('RAMU',22,'WARANGLE',87,'RAMU@GMAIL.COM');
SELECT * FROM STUDENT
WHERE CITY='HYDRABAD';
SELECT * FROM STUDENT
WHERE CITY='KHAMMAM';
SELECT * FROM STUDENT
WHERE MARKS>=85;
SELECT * FROM STUDENT
WHERE AGE>=24;

