-- IS NULL
-- NULL means no value / missing value.
CREATE DATABASE COLLAGE;
USE COLLAGE;
CREATE TABLE STUDENT(
ID INT PRIMARY KEY AUTO_INCREMENT,
-- IS NULL
-- NULL means no value / missing value.
NAME VARCHAR(100) NOT NULL,
AGE INT CHECK(AGE>=18),
CITY VARCHAR(100),
MARKS INT ,
EMAIL VARCHAR(100) UNIQUE
);
INSERT INTO STUDENT(NAME,AGE,CITY,MARKS,EMAIL)
VALUES
('SIVA',22,NULL,82,'SIVA@GMAIL.COM'),
('RAVI',25,'KHAMMAM',95,'RAVI@GMAIL.COM'),
('NAVEEN',23,'WARANGLE',80,'NAVEEN@GMAIL.COM'),
('DHANUSH',25,'KHAMMAM',85,NULL),
('SATISH',24,NULL,90,'SATISH@GMAIL.COM'),
('RAMU',22,'WARANGLE',87,'RAMU@GMAIL.COM'),
('RANI',27,'KHAMMAM',60,NULL),
('HEMA',22,'SATUPALLY',40,'HEMA@GMAIL.COM'),
('VIDYA',29,NULL,30,'VIDYA@GMAIL.COM');

SELECT * FROM STUDENT
WHERE  EMAIL IS NULL;

SELECT * FROM STUDENT
WHERE  CITY IS NULL;

SELECT * FROM STUDENT
WHERE  EMAIL IS NOT NULL;

SELECT * FROM STUDENT
WHERE  EMAIL IS NULL
OR  CITY IS  NULL;

SELECT * FROM STUDENT
WHERE  EMAIL IS NOT NULL
OR  CITY IS NOT NULL;
