CREATE DATABASE COLLEGE;
USE COLLEGE;
CREATE TABLE STUDENT(
	ID INT PRIMARY KEY,
    NAME VARCHAR(100),
    CITY VARCHAR(100),
    MARKS INT);
INSERT INTO STUDENT
VALUES
(1,'SIVA','HYD',92),
(2,'RAVI','KHAM',85),
(3,'NAVEEN','SPL',86),
(4,'NANI','WNGL',95),
(5,'MAHI','SPL',94);


SELECT * 
FROM STUDENT
WHERE MARKS<=(
SELECT MARKS
FROM STUDENT
WHERE NAME='SIVA');
