-- DEFAULT
CREATE DATABASE COLLAGE;
USE COLLAGE;
CREATE TABLE STUDENT(ID INT PRIMARY KEY AUTO_INCREMENT,NAME VARCHAR(100),AGE INT CHECK(AGE>=18),CITY VARCHAR(100) DEFAULT 'SATUPALLY');
INSERT INTO STUDENT(NAME,AGE)
VALUES
('SIVA',25),
('MANI',23),
('VENKY',35);
SELECT * FROM STUDENT;