-- WHERE + GROUP BY + HAVING
-- Consider only students with marks greater than 50, group them by city, and show cities having at least 2 such students.
CREATE DATABASE COLLEGE;
USE COLLEGE;
CREATE TABLE STUDENT(
	ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(100),
    AGE INT,
    CITY VARCHAR(100),
    MARKS INT
);
INSERT INTO STUDENT(NAME,AGE,CITY,MARKS)
VALUES
('SIVE',22,'HYDRABAD',85),
('RAVI',24,'KHAMMAM',90),
('NANI',25,'HYDRABAD',95),
('SATISH',27,'KHAMMAM',65),
('DHANESH',25,'WANANGLE',75),
('MANI',26,'HYDRABAD',35),
('RAM',22,'KHAMMAM',45),
('HEMA',29,'HYDRABAD',95),
('RAKESH',30,'WANANGLE',99);

SELECT CITY,COUNT(*) AS TOTAL_STUDENTS
FROM STUDENT
WHERE MARKS>50
GROUP BY CITY
HAVING COUNT(*)>=2;