-- GROUP BY
--  GROUP BY groups rows that have the same value in one or more columns.
-- It is commonly used with aggregate functions.
-- Basic syntax
-- SELECT column_name, AGGREGATE_FUNCTION(column_name)
-- FROM table_name
-- GROUP BY column_name;
CREATE DATABASE COLLEGE;
USE COLLEGE;
CREATE TABLE STUDENT(
	ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(100),
    AGE INT,
    CITY VARCHAR(100),
    MARKS INT
);
INSERT INTO STUDENT(NAME,AGE,CITY,MARKS)
VALUES
('SIVE',22,'HYDRABAD',85),
('RAVI',24,'KHAMMAM',90),
('NANI',25,'HYDRABAD',95),
('SATISH',27,'KHAMMAM',65),
('DHANESH',25,'WANANGLE',75),
('MANI',26,'HYDRABAD',35),
('RAM',22,'KHAMMAM',45),
('HEMA',29,'HYDRABAD',95),
('RAKESH',30,'WANANGLE',99);
SELECT * FROM STUDENT;