-- Real-Time Example — Company Employees

CREATE DATABASE COMPANY;
USE COMPANY;
CREATE TABLE EMPLOYEES (
	ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(100),
    DEPARTMENT VARCHAR(50),
    SALARY INT
);
INSERT INTO EMPLOYEES(NAME,DEPARTMENT,SALARY)
VALUES
('SIVA','IT',50000),
('RAVI','IT',60000),
('NAVEEN','HR',40000),
('HARI','HR',45000),
('RAJU','SALES',55000);

-- Number of employees in each department
SELECT DEPARTMENT,COUNT(*) AS TOTAL_EMPOLYEES
FROM EMPLOYEES
GROUP BY DEPARTMENT;

-- Average salary in each department
SELECT DEPARTMENT,AVG(SALARY) AS AVG_SALARY
FROM EMPLOYEES
GROUP BY DEPARTMENT;

-- Departments with average salary above ₹50,000
SELECT DEPARTMENT,AVG(SALARY) AS AVG_SALARY
FROM EMPLOYEES
GROUP BY DEPARTMENT
HAVING AVG(SALARY)>=50000;