-- CEIL()
-- CEIL() rounds a number up to the nearest integer.
CREATE DATABASE COLLAGE;
USE COLLAGE;
CREATE TABLE STUDENT
	(ID INT PRIMARY KEY AUTO_INCREMENT,
	NAME VARCHAR(100) NOT NULL,
	AGE INT CHECK(AGE>=10),
	CITY VARCHAR(100) NOT NULL,
	MARKS INT NOT NULL,
	EMAIL VARCHAR(100) NOT NULL);
INSERT INTO STUDENT(NAME,AGE,CITY,MARKS,EMAIL)
VALUES
('SIVA',22,'HYDRABAD',82.1215,'SIVA@GMAIL.COM'),
('RAVI',25,'KHAMMAM',95.154,'RAVI@GMAIL.COM'),
('NAVEEN',23,'WARANGLE',80.25,'NAVEEN@GMAIL.COM'),
('DHANUSH',25,'KHAMMAM',85.54,'DHANUSH@GMAIL.COM'),
('SATISH',24,'HYDRABAD',90.154863,'SATISH@GMAIL.COM'),
('RAMU',22,'WARANGLE',87.1544,'RAMU@GMAIL.COM'),
('RANI',27,'KHAMMAM',60,'RANI@GMAIL.COM'),
('HEMA',22,'SATUPALLY',40.15,'HEMA@GMAIL.COM'),
('VIDYA',29,'WARANGLE',30.151,'VIDYA@GMAIL.COM');

SELECT NAME,CEIL(MARKS) FROM STUDENT;
SELECT CEIL(95.4);
SELECT CEIL(95.9);



