-- Arithmetic Operators
CREATE DATABASE COMPENY;
USE COMPENY;
CREATE TABLE EMPLOYEES(
	EMPLOYEE_ID INT ,
    NAME VARCHAR(100),
    DEPARTMENT_ID INT,
    SALARY INT);
INSERT INTO EMPLOYEES
VALUES
(1,'SIVA',1,40000),
(2,'RAVI',2,50000),
(3,'NAAEEN',3,45000),
(4,'MAHI',3,60000),
(5,'NANI',1,65000);


-- Addition
SELECT NAME, SALARY, SALARY + 5000 AS new_SALARY
FROM EMPLOYEES;

-- Subtraction
SELECT NAME, SALARY, SALARY - 5000 AS new_SALARY
FROM EMPLOYEES;


-- Multiplication
SELECT NAME, SALARY, SALARY * 2 AS new_SALARY
FROM EMPLOYEES;

-- Division
SELECT NAME, SALARY, SALARY/2 AS new_SALARY
FROM EMPLOYEES;

-- Modulus (remainder)
SELECT NAME, SALARY, SALARY % 2 AS new_SALARY
FROM EMPLOYEES;