-- Comparison Operators
-- Used to compare two values. They usually return TRUE or FALSE.

CREATE DATABASE COMPENY;
USE COMPENY;
CREATE TABLE EMPLOYEES(
	EMPLOYEE_ID INT ,
    NAME VARCHAR(100),
    DEPARTMENT_ID INT,
    CIYT VARCHAR(100),
    SALARY INT);
INSERT INTO EMPLOYEES
VALUES
(1,'SIVA',1,'HYD',40000),
(2,'RAVI',2,'KHMM',50000),
(3,'NAAEEN',3,'SPL',45000),
(4,'MAHI',3,'SPL',60000),
(5,'NANI',1,'KHMM',65000);

-- Greater than
SELECT * 
FROM EMPLOYEES
WHERE SALARY >30000;

-- Less than 
SELECT * 
FROM EMPLOYEES
WHERE SALARY <50000;

-- Greater than or equal to
SELECT * 
FROM EMPLOYEES
WHERE SALARY >=50000;

-- Less than or equal to
SELECT * 
FROM EMPLOYEES
WHERE SALARY <=50000;

-- Not equal to
SELECT * 
FROM EMPLOYEES
WHERE SALARY != 50000;

-- Not equal to
SELECT * 
FROM EMPLOYEES
WHERE SALARY <>30000;