-- Special Operators

CREATE DATABASE COMPENY;
USE COMPENY;
CREATE TABLE EMPLOYEES(
	EMPLOYEE_ID INT ,
	NAME VARCHAR(100),
	DEPARTMENT_ID INT,
	CITY VARCHAR(100),
	SALARY INT,
    EMAIL VARCHAR(100));
INSERT INTO EMPLOYEES
VALUES
(1,'SIVA',1,'HYD',40000,'SIVA@GAMIL.COM'),
(2,'RAVI',2,'KHMM',50000,NULL),
(3,'NAAEEN',3,'SPL',45000,'NAVEEN@GMAIL.COM'),
(4,'MAHI',3,'SPL',60000,NULL),
(5,'NANI',1,'KHMM',65000,'NANI@GMAIL.COM');

-- IN
-- Checks whether a value matches any value in a list.
SELECT *
FROM EMPLOYEES
WHERE CITY IN('HYD','KHMM','SPL');

SELECT *
FROM EMPLOYEES
WHERE CITY IN('HYD','KHMM');

-- BETWEEN
-- Checks whether a value is within a range.

SELECT *
FROM EMPLOYEES
WHERE SALARY BETWEEN 50000 AND 100000;

-- LIKE
-- Used for pattern matching.
SELECT  *
FROM EMPLOYEES
WHERE NAME LIKE 'S%';

SELECT  *
FROM EMPLOYEES
WHERE NAME LIKE '%I';

SELECT *
FROM EMPLOYEES
WHERE NAME LIKE '%A%';

SELECT  *
FROM EMPLOYEES
WHERE NAME LIKE '____';

-- IS NULL
-- Checks for missing (NULL) values.
SELECT *
FROM EMPLOYEES
WHERE EMAIL IS NULL;

SELECT *
FROM EMPLOYEES
WHERE EMAIL IS NOT NULL;

