-- Assignment Operator
-- The = operator is also used when assigning values.
CREATE DATABASE COMPENY;
USE COMPENY;
CREATE TABLE EMPLOYEES(
	EMPLOYEE_ID INT ,
	NAME VARCHAR(100),
	DEPARTMENT_ID INT,
	CITY VARCHAR(100),
	SALARY INT,
    EMAIL VARCHAR(100));
INSERT INTO EMPLOYEES
VALUES
(1,'SIVA',1,'HYD',40000,'SIVA@GAMIL.COM'),
(2,'RAVI',2,'KHMM',50000,NULL),
(3,'NAAEEN',3,'SPL',45000,'NAVEEN@GMAIL.COM'),
(4,'MAHI',3,'SPL',60000,NULL),
(5,'NANI',1,'KHMM',65000,'NANI@GMAIL.COM');

SELECT *
FROM EMPLOYEES
WHERE CITY = 'KHMM';

